### ISSUE TITLE
Broken as of VIdeoJS ^8.0.4

### ISSUE THREAD

**Issue by tom-evaristo** [chrisboustead/videojs-hls-quality-selector#106]
Steps To Reproduce

1.  Clone Repository
2. Update package json `"video.js": "^8.0.4"`, and `"videojs-contrib-quality-levels": "^4.0.0"`
3. update index.html video src to `https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8` or any HLS+TS Videos
4.  npm install
5. npm start
6. Go To localhost:9999
7. Cannot select Video QUality

**Comment by dikamilo** [comment]
A workaround for this is to fork and remove `this.getHls()` call in plugin constructor. It will work just fine even with video.js v8.3. `videojs-hls-contrib` is not used and deprecated.

**Comment by Previesam** [comment]
@dikamilo When I switch my script tag to use the non-minified version so I can edit I get error _VideoJsButtonClass.call is not a constructor. I don't why I am getting that can you help?

**Comment by tom-evaristo** [comment]
An updated Version Please TEST

https://www.npmjs.com/package/videojs-quality-selector-hls

**Comment by chrisspiegl** [comment]
For anyone coming here later: the new package by @tom-evaristo appears to be working with v8 of video.js.
Maybe this can be merged into one at some point but for now, I am using the `videojs-quality-selector-hls` package mentioned in the commend above.
