### ISSUE TITLE
Selector does not show on Safari browser

### ISSUE THREAD

**Issue by asafart** [chrisboustead/videojs-hls-quality-selector#12]
Hi there,
For some reason, this plugin will not work on safari and when enabling the plugin it will show the Caption button instead of the Quality button.
Any idea on how to approach this?
Regards,
asaf

**Comment by asafart** [comment]
I'm using the latest version of video js

**Comment by laptrinhcomvn** [comment]
It's still not support Safari yet.

**Comment by chrisboustead** [comment]
Closing as duplicate of #13

**Comment by uguraktas** [comment]
> Closing as duplicate of #13

Not same topic, This topic about safari! 

Any solution about this?
