### ISSUE TITLE
Selector doesn't show on mobile

### ISSUE THREAD

**Issue by sheriffmarley** [chrisboustead/videojs-hls-quality-selector#13]
Hi,

i experienced that the selector won't show on smartphones. Tested with Opera, Firefox and Samsungs Browser with Galaxy S9. I wasn't able to to reproduce it on pc. 

Any ideas what wrong?

**Comment by rolandstarke** [comment]
Hi,

I guess its because some browsers have native support for hls streams. Adding `overrideNative: true` fixed it for me (chrome on android).

```html
<video id="player" class="video-js vjs-big-play-centered vjs-16-9" poster="sample/poster.jpg" controls>
        <source src="sample/playlist.m3u8">
    </video>

<script>
    var player = videojs('player', {
        fluid: true,
        controlBar: {
            'pictureInPictureToggle': false
        },
        html5: {
            hls: {
                overrideNative: true,
            }
        },
    });
    player.hlsQualitySelector();
</script>
```

**Comment by chrisboustead** [comment]
Yes, this is just a native HLS caveat.  Closing as no change needed.
