### ISSUE TITLE
change selector icon

### ISSUE THREAD

**Issue by jb-alvarado** [chrisboustead/videojs-hls-quality-selector#17]
Hi, first thank you for your work!

Is it possible to change the icon from the selector, without editing the code?
I would like to use the gear instead. Until now I have change this in the script by it self. But after an update I have to edit it again.

**Comment by DispatchCommit** [comment]
I created a PR with support for this #19

**Comment by chrisboustead** [comment]
Thanks @DispatchCommit and @jb-alvarado.  Merged.  Apologies for the delay.
