### ISSUE TITLE
Icon class assigned to wrong element

### ISSUE THREAD

**Issue by deltafactory** [chrisboustead/videojs-hls-quality-selector#2]
It looks like the class `vjs-icon-hd` is being set to the `vjs-menu-button` element resulting in an undersized icon.
https://github.com/chrisboustead/videojs-hls-quality-selector/blob/master/src/plugin.js#L89

Looking at the chapters button, the class should be set to the `vjs-icon-placeholder`. Manually changing the DOM shows the desired result, though I don't understand the API well enough to know the correct call within the plugin.

**Comment by deltafactory** [comment]
Looks like replacing that line with this will do the trick:
`    concreteButtonInstance.menuButton_.$('.vjs-icon-placeholder' ).className += " vjs-icon-hd";`

**Comment by chrisboustead** [comment]
Fixed in https://github.com/chrisboustead/videojs-hls-quality-selector/commit/ad52c4d3e24dde103cdb5e58fe692f49598d06dc
