### ISSUE TITLE
Lift restriction to activate only when the HLS tech exists

### ISSUE THREAD

**Issue by tri170391** [chrisboustead/videojs-hls-quality-selector#27]
We implemented the `videojs-contrib-quality-levels` for our custom source handler based on `Hls.js` according to their specs: https://github.com/videojs/videojs-contrib-quality-levels#supporting-quality-levels-for-your-source

However there is this check that would block your plugin from working with our source handler: https://github.com/chrisboustead/videojs-hls-quality-selector/blob/master/src/plugin.js#L28-L34

After attempting to fool the `getHls()` check our implementation works well with your picker so IDK if this logic is necessary.

**Comment by chrisboustead** [comment]
It would require a significant refactor to have this plugin work with native HLS.

**Comment by tri170391** [comment]
No not native HLS, we have an "alternative" to `contrib-hls` that is also based on MSE. And we implemented the `videojs-contrib-quality-levels` specifications. It works well if we "workaround" that check.

**Comment by chrisboustead** [comment]
I see- why use that over the well maintained https://github.com/videojs/http-streaming?

**Comment by tri170391** [comment]
Because it is an alternative to it, which allow to use the well-maintained `hls.js` with `video,js` as a UI.
