### ISSUE TITLE
the player.hlsQualitySelector(); does not show

### ISSUE THREAD

**Issue by Nyceane** [chrisboustead/videojs-hls-quality-selector#30]
```
  <script src="https://cdn.jsdelivr.net/npm/video.js@7.8.3/dist/video.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@videojs/http-streaming@1.11.2/dist/videojs-http-streaming.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/videojs-contrib-hls.js@3.2.0/dist/videojs-contrib-hlsjs.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/videojs-contrib-quality-levels@2.0.9/dist/videojs-contrib-quality-levels.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/videojs-hls-quality-selector@1.1.0/dist/videojs-hls-quality-selector.js"></script>

    var player = videojs('instructor-video');
    player.hlsQualitySelector();

```

if I include videojs-contrib-hlsjs.min.js the selector does not show, but no error message, is it possible to get this working with both http streaming and videojs hls js in?  I need certain libraries inside hlsjs which still works.

**Comment by alexhackney** [comment]
Did you get this to work?

**Comment by chrisboustead** [comment]
Feel free to open a PR but this plugin strictly depends on the usage of the `videojs-contrib-quality-levels` which depends on the media being transmuxed in browser.  

If you don't want to force transmuxing on HLS-native browsers then unfortunately this is not possible at this time.

https://github.com/chrisboustead/videojs-hls-quality-selector/issues/27#issuecomment-686505640
