### ISSUE TITLE
mux.js seems to be a dependency?!

### ISSUE THREAD

**Issue by Artem-Schander** [chrisboustead/videojs-hls-quality-selector#32]
Hi, I'm trying to get this package to work in my Vue JS project.
Here is what I get

```bash
Error: ENOENT: no such file or directory, open 'node_modules/mux.js/lib/mp4/caption-parser.js'
```

As soon as I install  `mux.js` manually, the error is gone. But I would like to keep my package.json clean. I'm sure, I will forget what it is.

**Comment by chrisboustead** [comment]
`mux.js` is a dependency of `@videojs/http-streaming` (required to play HLS on non-native browsers)

Are you sure you've got that installed correctly?

**Comment by Artem-Schander** [comment]
Thanks for the answer,
In the meantime I moved on to a different solution.
