### ISSUE TITLE
Packaged files for distribution?

### ISSUE THREAD

**Issue by aaronpk** [chrisboustead/videojs-hls-quality-selector#39]
Any chance of including the already-compiled files in a distribution for download? I'd really rather not have to add node to my environment, I'd much rather just copy the js and css files to my web server. Thanks!

**Comment by chrisboustead** [comment]
You could find whichever version you want in the json here and grab the tarball link: https://registry.npmjs.org/videojs-hls-quality-selector/

e.g.:
```
https://registry.npmjs.org/videojs-hls-quality-selector/-/videojs-hls-quality-selector-1.1.3.tgz
```

Otherwise, it's an NPM package, so if you want to work outside of node that's a case you'd need to workaround on your own :)

**Comment by josepowera** [comment]
would this work?

https://www.jsdelivr.com/package/npm/videojs-hls-quality-selector?path=dist&tab=collection
