### ISSUE TITLE
player.tech().hls is deprecated.

### ISSUE THREAD

**Issue by j4nr6n** [chrisboustead/videojs-hls-quality-selector#50]
I'm using video.js 7.11.4 and getting
`VIDEOJS: WARN: player.tech().hls is deprecated. Use player.tech().vhs instead.` [here](https://github.com/chrisboustead/videojs-hls-quality-selector/blob/master/src/plugin.js#L43)

**Comment by kylekirkby** [comment]
@j4nr6n - why did you close this? Did you fix this issue?
