### ISSUE TITLE
Sorting quality level

### ISSUE THREAD

**Issue by luckily** [chrisboustead/videojs-hls-quality-selector#6]
Hello 👋
I already pull request to resolve this issue. 
https://github.com/chrisboustead/videojs-hls-quality-selector/pull/5

Thank you. 🤝

**Comment by chrisboustead** [comment]
Merged/resolved!

Thanks!

**Comment by chrisboustead** [comment]
@luckily - Released at: [0.0.8](https://www.npmjs.com/package/videojs-hls-quality-selector/v/0.0.8)

Thanks again!
