### ISSUE TITLE
Displaying resolutions in controlbar

### ISSUE THREAD

**Issue by coddok** [chrisboustead/videojs-hls-quality-selector#7]
It's possible to display current (or selected) resolution in controlbar?
There is no matter the order of renditions, in 'auto' mode a '360p.m3u8' is always selected first.
Ok, looks like the resolutions are sorted, but why I see HD icon in controlbar? 360p resolution is not HD. I expect to see there 360p instead.

**Comment by chrisboustead** [comment]
I will explore this.

**Comment by chrisboustead** [comment]
@coddok this is supported as of v1.1.0.  You may initialize the plugin with `displayCurrentQuality` property set to true.
```
player.hlsQualitySelector({
    displayCurrentQuality: true,
});
```

**Comment by campones** [comment]
you should clarify this in the description because I m currrently using vjs6 and vjs-hls-contrib and had only the hd icon showing up
also, it s not working very well, not really adaptative streaming if I compare with http-selector plugin.
