### ISSUE TITLE
[Guide] How to use it with Vue 3 and TS

### ISSUE THREAD

**Issue by Drabuna** [chrisboustead/videojs-hls-quality-selector#71]
OK, so I spent some time trying to make this work.
Maybe this will help someone.

Install following dependencies `videojs-contrib-quality-levels` and `videojs-hls-quality-selector`
Install following dev dependencies `@types/videojs-contrib-quality-level` and `@types/videojs-hls-quality-selector`
 
Somewhere in the boot or init do the following:
```
import videojs from 'video.js';
import qualitySelector from 'videojs-hls-quality-selector';
import qualityLevels from 'videojs-contrib-quality-levels';

videojs.registerPlugin('qualityLevels', qualityLevels);
videojs.registerPlugin('hlsQualitySelector', qualitySelector);
```

Create an instance of the player, and wait till it's ready:
```
onMounted(() => {
    const options:videojs.PlayerOptions = {
        autoplay: false,
        controls: true,
        sources: [{
            src: props.playlistSrc,
        }],
    };
    player = videojs(videoPlayer.value!, options, onPlayerReady);
});

function onPlayerReady() {
  player.hlsQualitySelector( {displayCurrentQuality: true} );
}
```

**Comment by Devidian** [comment]
Finally got it working again thanks, but i still have a problem, either i have no plugin or i have it twice 
![image](https://user-images.githubusercontent.com/10413872/128928571-a22fe414-43df-4843-b0e0-48587a08c5a9.png)

i have registered both in main.ts but he complains that qualityLevels is already registered
![image](https://user-images.githubusercontent.com/10413872/128928705-c9904019-8fa0-4b37-88b5-7820e7f4a704.png)

of course i have only done it once, so if i remove the line i have no quality levels at all.

**Comment by Drabuna** [comment]
Had the same issue, this solves it:

```
if (!videojs.getPlugin('qualityLevels')) {
    videojs.registerPlugin('qualityLevels', qualityLevels);
  }
```

**Comment by draker4** [comment]
Ho I did all of that, in the main.ts in vue3 I wrote this : 
`import videojs from "video.js";
import "video.js/dist/video-js.css";
import qualitySelector from "videojs-hls-quality-selector";
import qualityLevels from "videojs-contrib-quality-levels";
videojs.registerPlugin("qualityLevels", qualityLevels);
videojs.registerPlugin("hlsQualitySelector", qualitySelector);`
Then in my component i did that : 
`  let player: Player;

  const videoOptions = {
    sources: [
      {
        src: "http://localhost:8000/videos/playlists/" + "70" + "/index.m3u8",
        type: "application/x-mpegURL",
      },
    ],
    preload: true,
    controls: true,
    loop: false,
    volume: 0.6,
    playbackRates: [0.5, 1.0, 1.5, 2.0],
    responsive: true,
    autoplay: false,
    aspectRation: "16:9",
    fluid: true,
  };
  player = videojs(videoPlayer.value!, videoOptions, onPlayerReady);

});

const onPlayerReady = () => {
  player.hlsQualitySelector({ displayCurrentQuality: true });
};`
But I have this error in the function onPlayerReady() : Cannot find name 'player'. Did you mean 'Player'?ts(2552)
And whatever i try i cannot add the quality selection in my video. Apart from that everything is workinh, I am streaming index.m3u8 file from my backend, the video is okay, just the resolution is missing...
