### ISSUE TITLE
Label function

### ISSUE THREAD

**Issue by Drabuna** [chrisboustead/videojs-hls-quality-selector#72]
As I expected, this became an issue:

I have a variety of videos in different aspect ratios.  A great example is - I have 16:9 videos, and everything works great with them. But I also have 9:16 (vertical) videos. I went through the code and noticed that labels that represent quality are strictly based on height.  So I get something like:

![quality](https://user-images.githubusercontent.com/54286/128612927-0faba48f-3a8a-4ef0-91da-850bb30e1796.png)

This is totally fine from my perspective, but end-user will be confused, since they are more used to standard labels like 360p, 480p, 720p, 1080p, and so on.

So, can we get a way to specify (override) the naming for each label? Something like a callback function that we can provide:

```
function (representation: Representation):string {
 return representation.width + "p";
}
```

**Comment by stierler** [comment]
I believe this will be fixed by https://github.com/chrisboustead/videojs-hls-quality-selector/pull/67 , which I see was updated to be synced up with master.. will work on getting it tested/merged soon.
